### PR TITLE
Minify JSON resources size

### PR DESCRIPTION
**Pull request by UnknownNPC**
PR related to the ticket #338.
Plugin runs in `test-compile` phase, so json resource tests use files after minify

### CODE REVIEW

**Comment by mafagafogigante** [comment]
I thought this regular expression could be fooled by escaped characters and I was right. If there are escaped quotes inside the JSON it will mess things up. The only way to do this correctly seems to be to parse the JSON then spit it out without spaces (using our JSON framework, for instance), but there doesn't seem to be a Maven plugin for this yet.

**Comment by UnknownNPC** [comment]
@mafagafogigante, you're right. I am planning to check mojo api at evening.
Also, I have pushed more smart regexp. We can use it as temporary solution.

**Comment by mafagafogigante** [comment]
This regular expression caused a `StackOverflowError` on the CI server. It may not be reproduced on our local installations, but it is possible that this will eventually happen everywhere as the files get bigger.

The regular expression engine shipped with Java makes heavy use of recursion and the new solution you provided fails on it.

Regular expressions have their use cases, but it's quite easy to break things with them and I would rather avoid them.

If we could develop a minimal Maven plugin that used our JSON parser to read and write the JSON sources (without any spaces) it would be great. Not only it would not break the JSON files, it would also be much more efficient and a lot safer.

**Comment by mafagafogigante** [comment]
Closing because #356 will resolve this.

**Pull request closed without merging**
