### PR TITLE
Tests for the JSON resources

### PR DESCRIPTION
**Pull request by mafagafogigante**
Starting a PR to track progress and simplify collaboration.

@UnknownNPC I would like to have this finished and merged eventually. I know you don't work on it during the weekends, but I think we can have this one merged by next Friday (27th), right?

Left to do (or change) and who can do it:
- [x] Remove the enumeration of file names @UnknownNPC 
- [x] Just create a JSON object in the test method @UnknownNPC 
- [x] GroupJsonRule could be renamed? @mafagafogigante
- [x] Use more local variables to reduce line wrapping (anyone, but I am OK with doing it myself)
- [x] Squash commits into a single cleaner, issue-closing commit @mafagafogigante

### CODE REVIEW

**Comment by UnknownNPC** [comment]
Hi @mafagafogigante!
Thank you for code review and I'm sorry that I didn't finish it to the end of this week (I had a lot of tasks at work). 
The last of files will be finished to the end of next Wednesday taking into account points about `Enum` & `JSON object` creation.

**Comment by UnknownNPC** [comment]
I have pushed tests for the last files. Also, I have tried to reduce the number of line wrapping. 

I should note (before I forget) that I skipped validation for `drop` attribute in `creatures.json` file,  because it will increase complexity of `CreaturesJsonFileTest` test (requires java constant per `drop` attribute array key):
```
"drops": [
		[
			: String (required, uppercase)
			: Double (required)
		]
	] (optional)
```

**Comment by mafagafogigante** [comment]
@UnknownNPC no problem. I will check this out and finish it later this week. Thanks!

**Comment by mafagafogigante** [comment]
Closing this as all these changes have been merged onto my tree through #348.

**Pull request closed without merging**
