### PR TITLE
Item conciseness, Tag implementation.

### PR DESCRIPTION
**Pull request by neurolytic**
Next step?: Alter resource format to include an array of tags, instead of separate lines for "weapon, food", etc. Have resource reader produce the HashSet and store it with the Item Model, so you only create each HashSet once, and also so you don't need all the "tags.add(...)" calls in the item constructor, just pull the whole set from blueprint instead.

### CODE REVIEW

**Comment by mafagafogigante** [comment]
On the right way. A great PR. Thanks a lot again. I want to discuss some stuff before merging, though.

What do you think about convenience methods? (This is only your opinion, so be honest). So we would change ``Item.isWeapon()``'s body and not replace it for a more verbose method.

I don't remember the code style by heart, but I think the enum formatting is off, may be wrong and this wouldn't be a great issue anyways.

About the decoupling, I think I didn't like it back then because of ``everything is a weapon``, but I kind of want it now.

**Comment by neurolytic** [comment]
I figured you might've had some reason to not do a WeaponComponent before, but that with the tags going in it'd be ideal going forward.

As far as convenience methods, my own instinct would probably be leaning against them. I tend to prefer the least amount of code necessary, but I could see the value, too. My concern would be once there are more tags, possibly many more, that you tread into the territory of either having a bazillion methods or deciding which tags to promote to their own convenience method. Plus having two ways to do the same thing (like hasTag(food) vs isFood() ) seems like a bad thing. If one dev does it one way and another the other...

One thing I find sort of ugly is having to have  weapon.getWeaponComponent().getDamage()  in AttackAlgorithm and Hero. But solving that didn't seem worth introducing a local variable or pulling getDamage() back up to the Item class. Perhaps if WeaponComponent can be made to handle any requests going to 'weapon', that local variable can just point straight to the component. That way, the Attack code only needs to know about the WeaponComponent, and not other parts of the item.

**Comment by neurolytic** [comment]
As for the enum formatting I double checked the style and think I'm in the clear. It doesn't specifiy a precise placement for statics or enums, top seemed appropriate and you tend to put statics at top of other files. Also style says one line, array-style enum declarations are okay. I could be wrong though, missing something or misinterpreting.

**Comment by mafagafogigante** [comment]
Agree with you on convenience methods.

One thing I find sort of ugly is having to have weapon.getWeaponComponent().getDamage() - just a minor downside. I don't care personally.

About the enum, my bad. Shameful indeed, you are perfectly right.

Then we arrive at my last point: naming, naming, naming. Maybe, Item.hasAttribute(Attribute) would be best. I also like having the enum out of Item, although it seems to be pretty justifiable to keep it the way it is. Mostly up to you right now, waiting for your feedback. Merging if you think you are done.

**Comment by neurolytic** [comment]
Well, I nested tag within Item because I think it's probable we will end up using the same concept with creatures and maybe other content too. So using "ItemTag" as an outside enum meant having "ItemTag" all over the Item page, instead of just being able to use "Tag" locally. If Tag remains local to item, then there can be Creature.Tag, maybe Location.Tag, and so on. Would make it easier to reuse some code, especially resource-reading stuff. Granted, this can all be separate enums as ItemTag, CreatureTag, LocationTag, but I suppose I find something more elegant about using the dot notation and keeping the tags right next to where they're carried. I'm not attached either way. Tag could be Attribute instead, although that's a lot of letters and will stretch out the tag checks; hasAttribute(Item.Attribute.PIERCING) or whatever.

**Comment by neurolytic** [comment]
I'm off to get ready for work at the moment, will look over your thoughts when I get back tonight.

**Comment by mafagafogigante** [comment]
OK, hope you have a good time at work.

**Comment by neurolytic** [comment]
Does Flag do anything for you?

**Comment by mafagafogigante** [comment]
Just as OK as Tag. Let's stick with Tag, shall we? Plus, everything in the issue is called tag, so inserting a synonym won't help us much.

**Comment by mafagafogigante** [comment]
This PR is really close to merging. Read about branching in GH workflow to learn even more about git if you haven't done that already.

**Pull request closed without merging**
